services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
      - /var/www/storage
    depends_on:
      - mysql
    networks:
      - appnet
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

volumes:
  mysql_data:

networks:
  appnet:
