/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTeachersRouteImport } from './routes/_public/teachers'
import { Route as PublicCoursesRouteImport } from './routes/_public/courses'
import { Route as PublicAuthRouteImport } from './routes/_public/_auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as PublicTeacherIdRouteImport } from './routes/_public/teacher.$id'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/_app/onboarding'
import { Route as AuthenticatedAppCourseRouteImport } from './routes/_authenticated/_app/course'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeachersRoute = PublicTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicTeacherIdRoute = PublicTeacherIdRouteImport.update({
  id: '/teacher/$id',
  path: '/teacher/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCourseRoute = AuthenticatedAppCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/courses': typeof PublicCoursesRoute
  '/teachers': typeof PublicTeachersRoute
  '/': typeof PublicIndexRoute
  '/course': typeof AuthenticatedAppCourseRoute
  '/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/teacher/$id': typeof PublicTeacherIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/courses': typeof PublicCoursesRoute
  '/teachers': typeof PublicTeachersRoute
  '/': typeof PublicIndexRoute
  '/course': typeof AuthenticatedAppCourseRoute
  '/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/teacher/$id': typeof PublicTeacherIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteWithChildren
  '/_public/courses': typeof PublicCoursesRoute
  '/_public/teachers': typeof PublicTeachersRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/_app/course': typeof AuthenticatedAppCourseRoute
  '/_authenticated/_app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/teacher/$id': typeof PublicTeacherIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/courses'
    | '/teachers'
    | '/'
    | '/course'
    | '/onboarding'
    | '/profile'
    | '/login'
    | '/register'
    | '/teacher/$id'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/courses'
    | '/teachers'
    | '/'
    | '/course'
    | '/onboarding'
    | '/profile'
    | '/login'
    | '/register'
    | '/teacher/$id'
    | '/dashboard'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_app'
    | '/_public/_auth'
    | '/_public/courses'
    | '/_public/teachers'
    | '/_public/'
    | '/_authenticated/_app/course'
    | '/_authenticated/_app/onboarding'
    | '/_authenticated/_app/profile'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/teacher/$id'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/teachers': {
      id: '/_public/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof PublicTeachersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses': {
      id: '/_public/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/teacher/$id': {
      id: '/_public/teacher/$id'
      path: '/teacher/$id'
      fullPath: '/teacher/$id'
      preLoaderRoute: typeof PublicTeacherIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/onboarding': {
      id: '/_authenticated/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/course': {
      id: '/_authenticated/_app/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof AuthenticatedAppCourseRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCourseRoute: typeof AuthenticatedAppCourseRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCourseRoute: AuthenticatedAppCourseRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicAuthRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicCoursesRoute: typeof PublicCoursesRoute
  PublicTeachersRoute: typeof PublicTeachersRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicTeacherIdRoute: typeof PublicTeacherIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicCoursesRoute: PublicCoursesRoute,
  PublicTeachersRoute: PublicTeachersRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicTeacherIdRoute: PublicTeacherIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
