/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTeachersRouteImport } from './routes/_public/teachers'
import { Route as PublicCoursesRouteImport } from './routes/_public/courses'
import { Route as PublicAuthRouteImport } from './routes/_public/_auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as PublicTeacherIdRouteImport } from './routes/_public/teacher.$id'
import { Route as PublicCourseIdRouteImport } from './routes/_public/course.$id'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as AuthenticatedDashboardDashboardRouteImport } from './routes/_authenticated/dashboard/_dashboard'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/_app/onboarding'
import { Route as AuthenticatedAppCourseRouteImport } from './routes/_authenticated/_app/course'
import { Route as AuthenticatedDashboardDashboardIndexRouteImport } from './routes/_authenticated/dashboard/_dashboard/index'
import { Route as PublicAuthAuthCallbackRouteImport } from './routes/_public/_auth/auth/callback'
import { Route as AuthenticatedDashboardDashboardTeachersRouteImport } from './routes/_authenticated/dashboard/_dashboard/teachers'
import { Route as AuthenticatedDashboardDashboardSubjectsRouteImport } from './routes/_authenticated/dashboard/_dashboard/subjects'
import { Route as AuthenticatedDashboardDashboardStudentsRouteImport } from './routes/_authenticated/dashboard/_dashboard/students'
import { Route as AuthenticatedDashboardDashboardCoursesRouteImport } from './routes/_authenticated/dashboard/_dashboard/courses'

const AuthenticatedDashboardRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeachersRoute = PublicTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicTeacherIdRoute = PublicTeacherIdRouteImport.update({
  id: '/teacher/$id',
  path: '/teacher/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCourseIdRoute = PublicCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const AuthenticatedDashboardDashboardRoute =
  AuthenticatedDashboardDashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCourseRoute = AuthenticatedAppCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedDashboardDashboardIndexRoute =
  AuthenticatedDashboardDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardRoute,
  } as any)
const PublicAuthAuthCallbackRoute = PublicAuthAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => PublicAuthRoute,
} as any)
const AuthenticatedDashboardDashboardTeachersRoute =
  AuthenticatedDashboardDashboardTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedDashboardDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardSubjectsRoute =
  AuthenticatedDashboardDashboardSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedDashboardDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardStudentsRoute =
  AuthenticatedDashboardDashboardStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedDashboardDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardCoursesRoute =
  AuthenticatedDashboardDashboardCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/courses': typeof PublicCoursesRoute
  '/teachers': typeof PublicTeachersRoute
  '/': typeof PublicIndexRoute
  '/course': typeof AuthenticatedAppCourseRoute
  '/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRouteWithChildren
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/course/$id': typeof PublicCourseIdRoute
  '/teacher/$id': typeof PublicTeacherIdRoute
  '/dashboard/courses': typeof AuthenticatedDashboardDashboardCoursesRoute
  '/dashboard/students': typeof AuthenticatedDashboardDashboardStudentsRoute
  '/dashboard/subjects': typeof AuthenticatedDashboardDashboardSubjectsRoute
  '/dashboard/teachers': typeof AuthenticatedDashboardDashboardTeachersRoute
  '/auth/callback': typeof PublicAuthAuthCallbackRoute
  '/dashboard/': typeof AuthenticatedDashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/courses': typeof PublicCoursesRoute
  '/teachers': typeof PublicTeachersRoute
  '/': typeof PublicIndexRoute
  '/course': typeof AuthenticatedAppCourseRoute
  '/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardIndexRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/course/$id': typeof PublicCourseIdRoute
  '/teacher/$id': typeof PublicTeacherIdRoute
  '/dashboard/courses': typeof AuthenticatedDashboardDashboardCoursesRoute
  '/dashboard/students': typeof AuthenticatedDashboardDashboardStudentsRoute
  '/dashboard/subjects': typeof AuthenticatedDashboardDashboardSubjectsRoute
  '/dashboard/teachers': typeof AuthenticatedDashboardDashboardTeachersRoute
  '/auth/callback': typeof PublicAuthAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteWithChildren
  '/_public/courses': typeof PublicCoursesRoute
  '/_public/teachers': typeof PublicTeachersRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/_app/course': typeof AuthenticatedAppCourseRoute
  '/_authenticated/_app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/_dashboard': typeof AuthenticatedDashboardDashboardRouteWithChildren
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/course/$id': typeof PublicCourseIdRoute
  '/_public/teacher/$id': typeof PublicTeacherIdRoute
  '/_authenticated/dashboard/_dashboard/courses': typeof AuthenticatedDashboardDashboardCoursesRoute
  '/_authenticated/dashboard/_dashboard/students': typeof AuthenticatedDashboardDashboardStudentsRoute
  '/_authenticated/dashboard/_dashboard/subjects': typeof AuthenticatedDashboardDashboardSubjectsRoute
  '/_authenticated/dashboard/_dashboard/teachers': typeof AuthenticatedDashboardDashboardTeachersRoute
  '/_public/_auth/auth/callback': typeof PublicAuthAuthCallbackRoute
  '/_authenticated/dashboard/_dashboard/': typeof AuthenticatedDashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/courses'
    | '/teachers'
    | '/'
    | '/course'
    | '/onboarding'
    | '/profile'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/course/$id'
    | '/teacher/$id'
    | '/dashboard/courses'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/auth/callback'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/courses'
    | '/teachers'
    | '/'
    | '/course'
    | '/onboarding'
    | '/profile'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/course/$id'
    | '/teacher/$id'
    | '/dashboard/courses'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/auth/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_app'
    | '/_public/_auth'
    | '/_public/courses'
    | '/_public/teachers'
    | '/_public/'
    | '/_authenticated/_app/course'
    | '/_authenticated/_app/onboarding'
    | '/_authenticated/_app/profile'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/_dashboard'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/course/$id'
    | '/_public/teacher/$id'
    | '/_authenticated/dashboard/_dashboard/courses'
    | '/_authenticated/dashboard/_dashboard/students'
    | '/_authenticated/dashboard/_dashboard/subjects'
    | '/_authenticated/dashboard/_dashboard/teachers'
    | '/_public/_auth/auth/callback'
    | '/_authenticated/dashboard/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/teachers': {
      id: '/_public/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof PublicTeachersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses': {
      id: '/_public/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/teacher/$id': {
      id: '/_public/teacher/$id'
      path: '/teacher/$id'
      fullPath: '/teacher/$id'
      preLoaderRoute: typeof PublicTeacherIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/course/$id': {
      id: '/_public/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof PublicCourseIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_authenticated/dashboard/_dashboard': {
      id: '/_authenticated/dashboard/_dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/onboarding': {
      id: '/_authenticated/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/course': {
      id: '/_authenticated/_app/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof AuthenticatedAppCourseRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/dashboard/_dashboard/': {
      id: '/_authenticated/dashboard/_dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardRoute
    }
    '/_public/_auth/auth/callback': {
      id: '/_public/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof PublicAuthAuthCallbackRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_authenticated/dashboard/_dashboard/teachers': {
      id: '/_authenticated/dashboard/_dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardTeachersRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardRoute
    }
    '/_authenticated/dashboard/_dashboard/subjects': {
      id: '/_authenticated/dashboard/_dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardSubjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardRoute
    }
    '/_authenticated/dashboard/_dashboard/students': {
      id: '/_authenticated/dashboard/_dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardRoute
    }
    '/_authenticated/dashboard/_dashboard/courses': {
      id: '/_authenticated/dashboard/_dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCourseRoute: typeof AuthenticatedAppCourseRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCourseRoute: AuthenticatedAppCourseRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedDashboardDashboardRouteChildren {
  AuthenticatedDashboardDashboardCoursesRoute: typeof AuthenticatedDashboardDashboardCoursesRoute
  AuthenticatedDashboardDashboardStudentsRoute: typeof AuthenticatedDashboardDashboardStudentsRoute
  AuthenticatedDashboardDashboardSubjectsRoute: typeof AuthenticatedDashboardDashboardSubjectsRoute
  AuthenticatedDashboardDashboardTeachersRoute: typeof AuthenticatedDashboardDashboardTeachersRoute
  AuthenticatedDashboardDashboardIndexRoute: typeof AuthenticatedDashboardDashboardIndexRoute
}

const AuthenticatedDashboardDashboardRouteChildren: AuthenticatedDashboardDashboardRouteChildren =
  {
    AuthenticatedDashboardDashboardCoursesRoute:
      AuthenticatedDashboardDashboardCoursesRoute,
    AuthenticatedDashboardDashboardStudentsRoute:
      AuthenticatedDashboardDashboardStudentsRoute,
    AuthenticatedDashboardDashboardSubjectsRoute:
      AuthenticatedDashboardDashboardSubjectsRoute,
    AuthenticatedDashboardDashboardTeachersRoute:
      AuthenticatedDashboardDashboardTeachersRoute,
    AuthenticatedDashboardDashboardIndexRoute:
      AuthenticatedDashboardDashboardIndexRoute,
  }

const AuthenticatedDashboardDashboardRouteWithChildren =
  AuthenticatedDashboardDashboardRoute._addFileChildren(
    AuthenticatedDashboardDashboardRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDashboardRoute: typeof AuthenticatedDashboardDashboardRouteWithChildren
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDashboardRoute:
      AuthenticatedDashboardDashboardRouteWithChildren,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicAuthRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthAuthCallbackRoute: typeof PublicAuthAuthCallbackRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthAuthCallbackRoute: PublicAuthAuthCallbackRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicCoursesRoute: typeof PublicCoursesRoute
  PublicTeachersRoute: typeof PublicTeachersRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCourseIdRoute: typeof PublicCourseIdRoute
  PublicTeacherIdRoute: typeof PublicTeacherIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicCoursesRoute: PublicCoursesRoute,
  PublicTeachersRoute: PublicTeachersRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCourseIdRoute: PublicCourseIdRoute,
  PublicTeacherIdRoute: PublicTeacherIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
